"""empty message

Revision ID: ac90e8056ef0
Revises: f1655d4aa31a
Create Date: 2020-01-15 20:53:33.806804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac90e8056ef0'
down_revision = 'f1655d4aa31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('object_name', sa.String(length=68), nullable=False))
    op.drop_column('objects', 'objectname')
    op.add_column('resource_centers', sa.Column('center_name', sa.String(length=200), nullable=False))
    op.drop_column('resource_centers', 'centername')
    op.add_column('users', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('users', sa.Column('lastname', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('resource_centers', sa.Column('centername', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('resource_centers', 'center_name')
    op.add_column('objects', sa.Column('objectname', mysql.VARCHAR(length=68), nullable=False))
    op.drop_column('objects', 'object_name')
    # ### end Alembic commands ###
