"""empty message

Revision ID: b4954b40e51c
Revises: ac90e8056ef0
Create Date: 2020-01-15 21:09:40.381885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4954b40e51c'
down_revision = 'ac90e8056ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource__centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('types', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('resource_centers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_centers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('address', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('zip', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('hours', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('phone_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('website', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('types', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('center_name', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('resource__centers')
    # ### end Alembic commands ###
